# Generated by Django 3.2.5 on 2021-07-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_central_ciudad_cluster_ce_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.BigIntegerField()),
                ('cobo', models.CharField(max_length=100, null=True)),
                ('fecha', models.CharField(max_length=40, null=True)),
                ('mes', models.CharField(max_length=8, null=True)),
                ('anio', models.IntegerField(null=True)),
                ('clli', models.CharField(max_length=25, null=True)),
                ('ing_cliente', models.CharField(max_length=60, null=True)),
                ('ing_cisco', models.CharField(max_length=60, null=True)),
                ('problema', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=20, null=True)),
                ('codigo_cierre', models.CharField(max_length=100, null=True)),
                ('subtipo', models.CharField(max_length=40, null=True)),
                ('detalle_subtipo', models.CharField(max_length=40, null=True)),
                ('tecnologia', models.CharField(max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tecnologia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clli', models.CharField(max_length=25)),
                ('ip_lb0', models.CharField(max_length=15)),
                ('ip_lb1', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=6)),
                ('avm', models.IntegerField()),
                ('sofware_version', models.CharField(max_length=15)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.central')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cluster')),
                ('modelo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modelo_equipo')),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='cluster_ce',
        ),
        migrations.AddField(
            model_name='cluster',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proyecto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
        migrations.AddField(
            model_name='central',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='divisional',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
    ]
