# Generated by Django 3.2.5 on 2021-07-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210713_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
