# Generated by Django 3.2.5 on 2021-07-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_central_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('divisional', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('central', models.CharField(max_length=30)),
                ('cluster', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=25)),
                ('ip_lb0', models.CharField(max_length=15)),
                ('casos', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
    ]
