# Generated by Django 3.2.5 on 2021-07-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumen_x_modelo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modelos', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'resumen_x_modelo',
                'managed': False,
            },
        ),
    ]
