# Generated by Django 3.2.5 on 2021-07-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resumen_x_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ne',
            name='unit',
            field=models.CharField(max_length=15),
        ),
    ]
