# Generated by Django 3.2.5 on 2021-07-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inventario_fisico2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventario_fisico2',
            new_name='inventario_fisico',
        ),
    ]
