# Generated by Django 3.2.5 on 2021-07-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_inventario_fisico2_inventario_fisico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventario_fisico',
        ),
    ]
