# Generated by Django 3.2.5 on 2021-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_inventario_fisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario_fisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(null=True)),
                ('anio', models.IntegerField(null=True)),
                ('clli', models.CharField(max_length=20)),
                ('chass_serial', models.CharField(max_length=15)),
                ('chassis', models.CharField(max_length=60)),
                ('card_serial', models.CharField(max_length=15)),
                ('slot', models.IntegerField(null=True)),
                ('card', models.CharField(max_length=150)),
                ('card_last_change', models.CharField(max_length=50)),
                ('module_name', models.CharField(max_length=50)),
                ('card_status', models.CharField(max_length=3)),
                ('connector', models.CharField(max_length=50)),
                ('conn_serial', models.CharField(max_length=15)),
                ('port_number', models.IntegerField(null=True)),
                ('port', models.CharField(max_length=50)),
                ('port_status', models.CharField(max_length=3)),
                ('plugg_type', models.CharField(max_length=5)),
                ('port_last_change', models.CharField(max_length=50)),
                ('mtu', models.IntegerField(null=True)),
                ('port_descrip', models.CharField(max_length=150)),
            ],
        ),
    ]
