# Generated by Django 3.2.5 on 2021-07-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_inventario_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_fisico',
            name='port_descrip',
            field=models.CharField(max_length=200),
        ),
    ]
