# Generated by Django 3.2.5 on 2021-07-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_inventario_fisico_port_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_fisico',
            name='card_status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inventario_fisico',
            name='port_status',
            field=models.CharField(max_length=15),
        ),
    ]
