# Generated by Django 3.2.5 on 2021-07-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210730_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_fisico',
            name='port_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='inventario_fisico',
            name='slot',
            field=models.IntegerField(default='0'),
        ),
    ]
