# Generated by Django 3.2.5 on 2021-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210730_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_fisico',
            name='card_status',
            field=models.CharField(max_length=30),
        ),
    ]
