# Generated by Django 3.2.5 on 2021-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_inventario_fisico_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_fisico',
            name='card_serial',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario_fisico',
            name='chass_serial',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario_fisico',
            name='conn_serial',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario_fisico',
            name='port_status',
            field=models.CharField(max_length=20),
        ),
    ]
